### ISSUE TITLE
I could not use Cuda

### ISSUE THREAD

**Issue by esmail-mkh** [VoxelCubes/PanelCleaner#21]
I have a RTX3060 but I couldn't use cuda as the core text recognizer, please help me if you can.

**Comment by VoxelCubes** [comment]
That's unfortunate, and unfortunately I'm no expert on the matter either. The best I can do is point you towards this stackoverflow question: https://stackoverflow.com/questions/60987997/why-torch-cuda-is-available-returns-false-even-after-installing-pytorch-with

It presents multiple ways to diagnose and solve the issue.
It's probably caused by your driver not getting along with the cuda interface the torch package expects, or the torch package wasn't installed with the cuda module, for some reason. That's probably what's going on. Good luck!

**Comment by VoxelCubes** [comment]
I found a workaround that should work:
```
pip uninstall torch torchvision -y
pip install torch torchvision --index-url https://download.pytorch.org/whl/cu118
```
Otherwise, try one of the pre-built binaries I'll be releasing over the next week.
