### ISSUE TITLE
I hope to have a Chinese version. Thank you for your efforts.

### ISSUE THREAD

**Issue by jxhxgt** [VoxelCubes/PanelCleaner#29]

**Comment by jxhxgt** [comment]
Excuse me if the adjustment mask is conservative, the program found the text very well, but did not deal with it

**Comment by VoxelCubes** [comment]
Hi, I'm not sure what would need to be adjusted, since you say it already finds the text, could you perhaps share an example image with a problem? Either post it here or send it to my email voxel.aur@gmail.com .
Alternatively, try adjusting the profile settings in the "Masking" section on the left of the gui.
Thank you.

**Comment by VoxelCubes** [comment]
Hey @jxhxgt, we have translation support, so all that's missing is a translator. Here is a little guide I put together: [translating](https://github.com/VoxelCubes/PanelCleaner/blob/master/translations/TRANSLATING.md)
