### ISSUE TITLE
Processing error message after bulk 

### ISSUE THREAD

**Issue by Traumtix** [VoxelCubes/PanelCleaner#67]
![Screenshot_2024-02-14-20-05-58-180_com anydesk anydeskandroid](https://github.com/VoxelCubes/PanelCleaner/assets/160123025/91337821-1d96-414d-a3db-e1d3bcfde16d)

i got this error message after putting a thousand of images into the panel cleaner and i got this error message. Here are my specs;
i5-8300H
Intel UHD Graphics 630
GTX 1050ti
24 GB ram
about 400 GB HDD free storage.

everything looked fine while it was running except the cpu going to 100% (i had my task manager open beside it). the ram stayed at 12GB i think, but it says "no space left on device". so what happened here?

**Comment by VoxelCubes** [comment]
Did you close the issue because you found the solution? I'm rather curious how that turned out.
"No space left" can mean that you ran out of file descriptors or similar for the current folder or file system structure. 

The largest number I have tested with so far is roughly 400 images, 1000+ is definitely exceptional.

**Comment by Traumtix** [comment]
sorry, I realized i was asking the wrong question.. so the problem is when the pcleaner is starting, the cache image files are saved in my Data C drive (which only has about 10 GB) so it makes sense why it says i don't have enough drive. my Data D drive is my HDD.

i tried to redownload and install python, pcleaner & pytorch in a virtual environment in my HDD but it gives a different error message. is there any way to change the cache directory path to another drive?

**Comment by VoxelCubes** [comment]
Dang, on Linux that would be easy since I use the configurable XDG paths, didn't consider windows in that. 
Ah, I know, gimme a sec.

Ok. If you clone this from git and run from source, or wait until I release version 2.3.0 in a few days, you can then set the environment variable `XDG_CACHE_HOME` on windows and macos too and it will then place the cache folder there instead.
I can't help you with how to set environment variables in Windows, but with bash at least it's as simple as 
```
XDG_CACHE_HOME=~/my/own/cache/folder pcleaner clean myimgs
```
The gui will respect it too, btw.

**Comment by Traumtix** [comment]
I'll try that out! thank you.

**Comment by VoxelCubes** [comment]
Version 2.3.0 is live now btw, so no need for source.
