### ISSUE TITLE
allow us to select or mark texts

### ISSUE THREAD

**Issue by aymanharrawi** [VoxelCubes/PanelCleaner#80]
can't it just allow us to choose select or mark bubbles that contain texts? because it can't detect all of them so selecting them manually is better, also for osr

**Comment by VoxelCubes** [comment]
Panel Cleaner is designed to not have a human tweak individual bubbles or mess with pixels directly, since that's better done in a proper image editor anyway.

Also, the way the gui works now, where you'd need to manually open each image, would be a User Experience nightmare. I don't want to incourage that.
A new UI would need to be developed for that kind of work flow. 

I'm not particularly interested in building out that aspect of Panel Cleaner. A separate app would be better, one that allows for support of lots of different OCR engines.

Check out Ballons Translator while you're at it, I think they offer proper manual work like that. Hope it works out!
